
Parameters:
  MyKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Keypair for the EC2 instnace.

  VPCBlock:
    Type: String
    Default: 10.0.0.0/16
    Description: VPC CIDR Range

  Subnet01Block:
    Type: String
    Default: 10.0.1.0/24
    Description: Subnet01 CIDR Range
  
  MyInstanceType:
    Type: String
    Description: Select the instance type for the EC2 instnace.
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3.nano

Mappings:
  MyImageId:
    us-east-2:
      HVM64: ami-022661f8a4a1b91cf
    us-west-1:
      HVM64: ami-0c7f9161f8491665f



Resources:
  MyVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
      Parameters:
        VPCBlock: !Ref VPCBlock
        Subnet01Block: !Ref Subnet01Block
    TimeOutInMinutes: 5

  MySGStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
      Parameters:
        VPCId: !GetAtt MyVPCStack.Outputs.VPCId
    TimeOutInMinutes: 5



  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - MyImageId
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: !Ref MyInstanceType
      KeyName: !Ref MyKeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !GetAtt MyVPCStack.Outputs.Subnet01Id
          GroupSet:
            - !GetAtt MYSGStack.Outputs.SGOutput

      

      UserData:
        Fn::Base64: | 
          #!/bin/bash
          yum install httpd -y
          service httpd start
          chkconfig httpd on
          echo "<h1>Webserver Launched using CFN template</h1>" > /var/www/html/index.html

Outputs:
  AppURL:
    Value: !Sub "https://${MyEC2Instance.PublicDnsName}:443/index.html"
    Description: Application URL to Access.
