
Parameters:
  VPCBlock:
    Type: String
    Default: 10.0.0.0/16
    Description: VPC CIDR Range

  Subnet01Block:
    Type: String
    Default: 10.0.1.0/24
    Description: Subnet01 CIDR Range

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Dev VPC Network Configuration
          Parameters:
            - VPCBlock
            - Subnet01Block        
    ParameterLabels:
      VPCBlock:
        default: VPC CIDR Range selection  


Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags: 
        - Key: Name
          Value: !Sub "${AWS::StackName}-MyVPC"

  Subnet01:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref Subnet01Block
      VpcId: !Ref MyVPC
      AvailabilityZone:
        Fn::Select:
          - '0'
          - Fn::GetAZs:
              Ref: AWS::Region
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Subnet01"
  
  MyRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-MyRouteTable"
  
  MySubnetRTA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref MyRouteTable
      SubnetId: !Ref Subnet01


  MyInternetGW:
    Type: AWS::EC2::InternetGateway
  
  MyVPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref MyInternetGW
      VpcId: !Ref MyVPC
  

  MyRoute:
    DependsOn: MyVPCGatewayAttachment
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref MyRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyInternetGW

Outputs:
  Subnet01Id:
    Description: Subnet01 Id
    Value: !Ref Subnet01
  
  VPCId:
    Description: VPCId
    Value: !Ref MyVPC